# Generated by Django 4.1.7 on 2023-03-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('pk',)},
        ),
    ]
