# Generated by Django 4.1.7 on 2023-03-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_about_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('cat_name',)},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='cat_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='prod_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prod_price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
